services:
  downloader:
    build: .
    ports:
      - "9199:3000"
    volumes:
      - ./vol1/1000/m3u8/downloads:/app/downloads
      - ./vol1/1000/m3u8/downloads/temp:/app/temp
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - video
    restart: always
